-- [프로그래머스 Lv3/SQL] 있었는데요 없었습니다
-- https://programmers.co.kr/learn/courses/30/lessons/59043

SELECT INS.ANIMAL_ID, INS.NAME
FROM ANIMAL_INS AS INS, ANIMAL_OUTS AS OUTS
WHERE INS.ANIMAL_ID = OUTS.ANIMAL_ID AND OUTS.DATETIME < INS.DATETIME
ORDER BY INS.DATETIME
